# Generated by Django 4.2.27 on 2026-02-13 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bus_id', models.CharField(max_length=50, unique=True)),
                ('route', models.CharField(max_length=100)),
                ('bus_type', models.CharField(max_length=50)),
                ('depot', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('capacity', models.PositiveIntegerField()),
                ('passengers', models.PositiveIntegerField()),
                ('occupancy_rate', models.FloatField()),
                ('distance_km', models.FloatField()),
                ('fare_per_passenger', models.DecimalField(decimal_places=2, max_digits=8)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_consumed_liters', models.FloatField()),
                ('month', models.CharField(max_length=20)),
                ('day_of_week', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bus')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
